/** ISO 4217 currencies with display symbols for dropdowns. */
export const CURRENCY_CATALOG = [
  { code: 'INR', symbol: '₹', name: 'Indian Rupee' },
  { code: 'USD', symbol: '$', name: 'US Dollar' },
  { code: 'EUR', symbol: '€', name: 'Euro' },
  { code: 'GBP', symbol: '£', name: 'British Pound' },
  { code: 'AED', symbol: 'د.إ', name: 'UAE Dirham' },
  { code: 'AUD', symbol: 'A$', name: 'Australian Dollar' },
  { code: 'CAD', symbol: 'C$', name: 'Canadian Dollar' },
  { code: 'CHF', symbol: 'Fr', name: 'Swiss Franc' },
  { code: 'CNY', symbol: '¥', name: 'Chinese Yuan' },
  { code: 'JPY', symbol: '¥', name: 'Japanese Yen' },
  { code: 'SGD', symbol: 'S$', name: 'Singapore Dollar' },
  { code: 'HKD', symbol: 'HK$', name: 'Hong Kong Dollar' },
  { code: 'SAR', symbol: '﷼', name: 'Saudi Riyal' },
  { code: 'QAR', symbol: '﷼', name: 'Qatari Riyal' },
  { code: 'KWD', symbol: 'د.ك', name: 'Kuwaiti Dinar' },
  { code: 'BHD', symbol: '.د.ب', name: 'Bahraini Dinar' },
  { code: 'OMR', symbol: '﷼', name: 'Omani Rial' },
  { code: 'MYR', symbol: 'RM', name: 'Malaysian Ringgit' },
  { code: 'THB', symbol: '฿', name: 'Thai Baht' },
  { code: 'IDR', symbol: 'Rp', name: 'Indonesian Rupiah' },
  { code: 'KRW', symbol: '₩', name: 'South Korean Won' },
  { code: 'NZD', symbol: 'NZ$', name: 'New Zealand Dollar' },
  { code: 'ZAR', symbol: 'R', name: 'South African Rand' },
  { code: 'BRL', symbol: 'R$', name: 'Brazilian Real' },
  { code: 'MXN', symbol: 'Mex$', name: 'Mexican Peso' },
  { code: 'RUB', symbol: '₽', name: 'Russian Ruble' },
  { code: 'TRY', symbol: '₺', name: 'Turkish Lira' },
  { code: 'PLN', symbol: 'zł', name: 'Polish Zloty' },
  { code: 'SEK', symbol: 'kr', name: 'Swedish Krona' },
  { code: 'NOK', symbol: 'kr', name: 'Norwegian Krone' },
  { code: 'DKK', symbol: 'kr', name: 'Danish Krone' },
  { code: 'CZK', symbol: 'Kč', name: 'Czech Koruna' },
  { code: 'HUF', symbol: 'Ft', name: 'Hungarian Forint' },
  { code: 'ILS', symbol: '₪', name: 'Israeli Shekel' },
  { code: 'EGP', symbol: 'E£', name: 'Egyptian Pound' },
  { code: 'NGN', symbol: '₦', name: 'Nigerian Naira' },
  { code: 'KES', symbol: 'KSh', name: 'Kenyan Shilling' },
  { code: 'PKR', symbol: '₨', name: 'Pakistani Rupee' },
  { code: 'BDT', symbol: '৳', name: 'Bangladeshi Taka' },
  { code: 'LKR', symbol: 'Rs', name: 'Sri Lankan Rupee' },
  { code: 'NPR', symbol: 'Rs', name: 'Nepalese Rupee' },
  { code: 'MUR', symbol: '₨', name: 'Mauritian Rupee' },
  { code: 'VND', symbol: '₫', name: 'Vietnamese Dong' },
  { code: 'PHP', symbol: '₱', name: 'Philippine Peso' },
  { code: 'TWD', symbol: 'NT$', name: 'Taiwan Dollar' },
  { code: 'ARS', symbol: '$', name: 'Argentine Peso' },
  { code: 'CLP', symbol: '$', name: 'Chilean Peso' },
  { code: 'COP', symbol: '$', name: 'Colombian Peso' },
  { code: 'PEN', symbol: 'S/', name: 'Peruvian Sol' },
  { code: 'RON', symbol: 'lei', name: 'Romanian Leu' },
  { code: 'BGN', symbol: 'лв', name: 'Bulgarian Lev' },
  { code: 'HRK', symbol: 'kn', name: 'Croatian Kuna' },
  { code: 'UAH', symbol: '₴', name: 'Ukrainian Hryvnia' },
  { code: 'GHS', symbol: '₵', name: 'Ghanaian Cedi' },
  { code: 'MAD', symbol: 'د.م.', name: 'Moroccan Dirham' },
  { code: 'TND', symbol: 'د.ت', name: 'Tunisian Dinar' },
  { code: 'JOD', symbol: 'JD', name: 'Jordanian Dinar' },
  { code: 'LBP', symbol: 'ل.ل', name: 'Lebanese Pound' },
  { code: 'IQD', symbol: 'ع.د', name: 'Iraqi Dinar' },
  { code: 'IRR', symbol: '﷼', name: 'Iranian Rial' },
  { code: 'AFN', symbol: '؋', name: 'Afghan Afghani' },
  { code: 'MMK', symbol: 'K', name: 'Myanmar Kyat' },
  { code: 'KHR', symbol: '៛', name: 'Cambodian Riel' },
  { code: 'LAK', symbol: '₭', name: 'Lao Kip' },
  { code: 'BND', symbol: 'B$', name: 'Brunei Dollar' },
  { code: 'FJD', symbol: 'FJ$', name: 'Fijian Dollar' },
  { code: 'XOF', symbol: 'CFA', name: 'West African CFA Franc' },
  { code: 'XAF', symbol: 'FCFA', name: 'Central African CFA Franc' },
  { code: 'XCD', symbol: 'EC$', name: 'East Caribbean Dollar' },
  { code: 'BBD', symbol: 'Bds$', name: 'Barbadian Dollar' },
  { code: 'JMD', symbol: 'J$', name: 'Jamaican Dollar' },
  { code: 'TTD', symbol: 'TT$', name: 'Trinidad Dollar' },
  { code: 'BSD', symbol: 'B$', name: 'Bahamian Dollar' },
  { code: 'BZD', symbol: 'BZ$', name: 'Belize Dollar' },
  { code: 'GTQ', symbol: 'Q', name: 'Guatemalan Quetzal' },
  { code: 'HNL', symbol: 'L', name: 'Honduran Lempira' },
  { code: 'NIO', symbol: 'C$', name: 'Nicaraguan Cordoba' },
  { code: 'CRC', symbol: '₡', name: 'Costa Rican Colon' },
  { code: 'PAB', symbol: 'B/.', name: 'Panamanian Balboa' },
  { code: 'DOP', symbol: 'RD$', name: 'Dominican Peso' },
  { code: 'HTG', symbol: 'G', name: 'Haitian Gourde' },
  { code: 'BOB', symbol: 'Bs.', name: 'Bolivian Boliviano' },
  { code: 'PYG', symbol: '₲', name: 'Paraguayan Guarani' },
  { code: 'UYU', symbol: '$U', name: 'Uruguayan Peso' },
  { code: 'VES', symbol: 'Bs.S', name: 'Venezuelan Bolivar' },
  { code: 'ISK', symbol: 'kr', name: 'Icelandic Krona' },
  { code: 'RSD', symbol: 'din', name: 'Serbian Dinar' },
  { code: 'BAM', symbol: 'KM', name: 'Bosnia Mark' },
  { code: 'MKD', symbol: 'ден', name: 'Macedonian Denar' },
  { code: 'ALL', symbol: 'L', name: 'Albanian Lek' },
  { code: 'GEL', symbol: '₾', name: 'Georgian Lari' },
  { code: 'AMD', symbol: '֏', name: 'Armenian Dram' },
  { code: 'AZN', symbol: '₼', name: 'Azerbaijani Manat' },
  { code: 'KZT', symbol: '₸', name: 'Kazakhstani Tenge' },
  { code: 'UZS', symbol: 'soʻm', name: 'Uzbekistani Som' },
  { code: 'TMT', symbol: 'm', name: 'Turkmenistani Manat' },
  { code: 'MNT', symbol: '₮', name: 'Mongolian Tugrik' },
  { code: 'BWP', symbol: 'P', name: 'Botswana Pula' },
  { code: 'NAD', symbol: 'N$', name: 'Namibian Dollar' },
  { code: 'ZMW', symbol: 'ZK', name: 'Zambian Kwacha' },
  { code: 'TZS', symbol: 'TSh', name: 'Tanzanian Shilling' },
  { code: 'UGX', symbol: 'USh', name: 'Ugandan Shilling' },
  { code: 'ETB', symbol: 'Br', name: 'Ethiopian Birr' },
  { code: 'RWF', symbol: 'FRw', name: 'Rwandan Franc' },
  { code: 'MZN', symbol: 'MT', name: 'Mozambican Metical' },
  { code: 'AOA', symbol: 'Kz', name: 'Angolan Kwanza' },
  { code: 'CDF', symbol: 'FC', name: 'Congolese Franc' },
  { code: 'SOS', symbol: 'Sh', name: 'Somali Shilling' },
  { code: 'SCR', symbol: '₨', name: 'Seychellois Rupee' },
  { code: 'MVR', symbol: 'Rf', name: 'Maldivian Rufiyaa' },
  { code: 'BTN', symbol: 'Nu.', name: 'Bhutanese Ngultrum' },
  { code: 'PGK', symbol: 'K', name: 'Papua New Guinean Kina' },
  { code: 'WST', symbol: 'T', name: 'Samoan Tala' },
  { code: 'TOP', symbol: 'T$', name: 'Tongan Paʻanga' },
  { code: 'VUV', symbol: 'VT', name: 'Vanuatu Vatu' },
  { code: 'SBD', symbol: 'SI$', name: 'Solomon Islands Dollar' },
  { code: 'KMF', symbol: 'CF', name: 'Comorian Franc' },
  { code: 'DJF', symbol: 'Fdj', name: 'Djiboutian Franc' },
  { code: 'ERN', symbol: 'Nfk', name: 'Eritrean Nakfa' },
  { code: 'GMD', symbol: 'D', name: 'Gambian Dalasi' },
  { code: 'GNF', symbol: 'FG', name: 'Guinean Franc' },
  { code: 'LRD', symbol: 'L$', name: 'Liberian Dollar' },
  { code: 'LSL', symbol: 'L', name: 'Lesotho Loti' },
  { code: 'MWK', symbol: 'MK', name: 'Malawian Kwacha' },
  { code: 'MRU', symbol: 'UM', name: 'Mauritanian Ouguiya' },
  { code: 'SZL', symbol: 'E', name: 'Swazi Lilangeni' },
  { code: 'BIF', symbol: 'FBu', name: 'Burundian Franc' },
  { code: 'CVE', symbol: '$', name: 'Cape Verdean Escudo' },
  { code: 'STN', symbol: 'Db', name: 'Sao Tome Dobra' },
  { code: 'GYD', symbol: 'G$', name: 'Guyanese Dollar' },
  { code: 'SRD', symbol: '$', name: 'Surinamese Dollar' },
  { code: 'AWG', symbol: 'ƒ', name: 'Aruban Florin' },
  { code: 'ANG', symbol: 'ƒ', name: 'Netherlands Antillean Guilder' },
  { code: 'KYD', symbol: 'CI$', name: 'Cayman Islands Dollar' },
  { code: 'BMD', symbol: 'BD$', name: 'Bermudian Dollar' },
  { code: 'FKP', symbol: '£', name: 'Falkland Islands Pound' },
  { code: 'GIP', symbol: '£', name: 'Gibraltar Pound' },
  { code: 'SHP', symbol: '£', name: 'Saint Helena Pound' },
  { code: 'IMP', symbol: '£', name: 'Isle of Man Pound' },
  { code: 'JEP', symbol: '£', name: 'Jersey Pound' },
  { code: 'GGP', symbol: '£', name: 'Guernsey Pound' },
];

const CODE_MAP = Object.fromEntries(CURRENCY_CATALOG.map((c) => [c.code, c]));

export function getCurrencyMeta(code) {
  const c = CODE_MAP[String(code || 'INR').toUpperCase()];
  return c || { code: String(code || 'INR').toUpperCase(), symbol: String(code || 'INR').toUpperCase(), name: code };
}

export function getCurrencySymbol(code) {
  return getCurrencyMeta(code).symbol;
}

/** Dropdown labels: "INR (₹)" */
export function formatCurrencyLabel(code) {
  const c = CODE_MAP[String(code || '').toUpperCase()];
  if (!c) return String(code || '').trim() || 'INR (₹)';
  return `${c.code} (${c.symbol})`;
}

export function parseCurrencyCode(value) {
  if (!value) return 'INR';
  const raw = String(value).trim();
  const m = raw.match(/^([A-Z]{3})/i);
  if (m) return m[1].toUpperCase();
  const byLabel = CURRENCY_CATALOG.find(
    (c) => formatCurrencyLabel(c.code).toLowerCase() === raw.toLowerCase() || c.code.toLowerCase() === raw.toLowerCase()
  );
  return byLabel?.code || raw.toUpperCase();
}

export const CURRENCY_SELECT_LABELS = CURRENCY_CATALOG.map((c) => formatCurrencyLabel(c.code));

/** Countries with primary invoice currency (ISO 4217). */
export const COUNTRY_CURRENCY_MAP = {
  India: 'INR',
  'United States': 'USD',
  'United Kingdom': 'GBP',
  Germany: 'EUR',
  France: 'EUR',
  Italy: 'EUR',
  Spain: 'EUR',
  Netherlands: 'EUR',
  Belgium: 'EUR',
  Austria: 'EUR',
  Ireland: 'EUR',
  Portugal: 'EUR',
  Greece: 'EUR',
  Finland: 'EUR',
  Luxembourg: 'EUR',
  Slovenia: 'EUR',
  Slovakia: 'EUR',
  Estonia: 'EUR',
  Latvia: 'EUR',
  Lithuania: 'EUR',
  Malta: 'EUR',
  Cyprus: 'EUR',
  Croatia: 'EUR',
  'United Arab Emirates': 'AED',
  'Saudi Arabia': 'SAR',
  Qatar: 'QAR',
  Kuwait: 'KWD',
  Bahrain: 'BHD',
  Oman: 'OMR',
  Japan: 'JPY',
  China: 'CNY',
  'Hong Kong': 'HKD',
  Singapore: 'SGD',
  Malaysia: 'MYR',
  Thailand: 'THB',
  Indonesia: 'IDR',
  Vietnam: 'VND',
  Philippines: 'PHP',
  'South Korea': 'KRW',
  Taiwan: 'TWD',
  Australia: 'AUD',
  'New Zealand': 'NZD',
  Canada: 'CAD',
  Mexico: 'MXN',
  Brazil: 'BRL',
  Argentina: 'ARS',
  Chile: 'CLP',
  Colombia: 'COP',
  Peru: 'PEN',
  'South Africa': 'ZAR',
  Nigeria: 'NGN',
  Kenya: 'KES',
  Egypt: 'EGP',
  Morocco: 'MAD',
  Tunisia: 'TND',
  Ghana: 'GHS',
  Pakistan: 'PKR',
  Bangladesh: 'BDT',
  'Sri Lanka': 'LKR',
  Nepal: 'NPR',
  Bhutan: 'BTN',
  Maldives: 'MVR',
  Afghanistan: 'AFN',
  Iran: 'IRR',
  Iraq: 'IQD',
  Israel: 'ILS',
  Jordan: 'JOD',
  Lebanon: 'LBP',
  Turkey: 'TRY',
  Russia: 'RUB',
  Ukraine: 'UAH',
  Poland: 'PLN',
  'Czech Republic': 'CZK',
  Hungary: 'HUF',
  Romania: 'RON',
  Bulgaria: 'BGN',
  Serbia: 'RSD',
  Switzerland: 'CHF',
  Sweden: 'SEK',
  Norway: 'NOK',
  Denmark: 'DKK',
  Iceland: 'ISK',
  Georgia: 'GEL',
  Armenia: 'AMD',
  Azerbaijan: 'AZN',
  Kazakhstan: 'KZT',
  Uzbekistan: 'UZS',
  Mongolia: 'MNT',
  Myanmar: 'MMK',
  Cambodia: 'KHR',
  Laos: 'LAK',
  Brunei: 'BND',
  Fiji: 'FJD',
  Mauritius: 'MUR',
  Seychelles: 'SCR',
  Botswana: 'BWP',
  Namibia: 'NAD',
  Zambia: 'ZMW',
  Tanzania: 'TZS',
  Uganda: 'UGX',
  Ethiopia: 'ETB',
  Rwanda: 'RWF',
  Mozambique: 'MZN',
  Angola: 'AOA',
  'Democratic Republic of the Congo': 'CDF',
  Somalia: 'SOS',
  'Papua New Guinea': 'PGK',
  Samoa: 'WST',
  Tonga: 'TOP',
  Vanuatu: 'VUV',
  'Solomon Islands': 'SBD',
  Jamaica: 'JMD',
  'Trinidad and Tobago': 'TTD',
  Barbados: 'BBD',
  Bahamas: 'BSD',
  Belize: 'BZD',
  Guatemala: 'GTQ',
  Honduras: 'HNL',
  Nicaragua: 'NIO',
  'Costa Rica': 'CRC',
  Panama: 'PAB',
  'Dominican Republic': 'DOP',
  Haiti: 'HTG',
  Bolivia: 'BOB',
  Paraguay: 'PYG',
  Uruguay: 'UYU',
  Venezuela: 'VES',
  Guyana: 'GYD',
  Suriname: 'SRD',
  Cuba: 'USD',
  Albania: 'ALL',
  'Bosnia and Herzegovina': 'BAM',
  'North Macedonia': 'MKD',
  Moldova: 'MDL',
  Belarus: 'BYN',
  Kyrgyzstan: 'KGS',
  Tajikistan: 'TJS',
  Turkmenistan: 'TMT',
  Yemen: 'YER',
  Syria: 'SYP',
  Libya: 'LYD',
  Algeria: 'DZD',
  Sudan: 'SDG',
  'South Sudan': 'SSP',
  Senegal: 'XOF',
  "Côte d'Ivoire": 'XOF',
  Mali: 'XOF',
  'Burkina Faso': 'XOF',
  Niger: 'XOF',
  Benin: 'XOF',
  Togo: 'XOF',
  Guinea: 'GNF',
  'Sierra Leone': 'SLE',
  Liberia: 'LRD',
  Gambia: 'GMD',
  Mauritania: 'MRU',
  Cameroon: 'XAF',
  Chad: 'XAF',
  Gabon: 'XAF',
  'Republic of the Congo': 'XAF',
  'Central African Republic': 'XAF',
  'Equatorial Guinea': 'XAF',
  Madagascar: 'MGA',
  Malawi: 'MWK',
  Lesotho: 'LSL',
  Eswatini: 'SZL',
  Burundi: 'BIF',
  Djibouti: 'DJF',
  Eritrea: 'ERN',
  Comoros: 'KMF',
  'Cape Verde': 'CVE',
  'Sao Tome and Principe': 'STN',
  Monaco: 'EUR',
  'San Marino': 'EUR',
  'Vatican City': 'EUR',
  Andorra: 'EUR',
  Liechtenstein: 'CHF',
  'New Caledonia': 'XPF',
  'French Polynesia': 'XPF',
  Guam: 'USD',
  'Puerto Rico': 'USD',
  Greenland: 'DKK',
  'Faroe Islands': 'DKK',
  Aruba: 'AWG',
  Curaçao: 'ANG',
  'Cayman Islands': 'KYD',
  Bermuda: 'BMD',
  'Isle of Man': 'IMP',
  Jersey: 'JEP',
  Guernsey: 'GGP',
  Gibraltar: 'GIP',
  'Falkland Islands': 'FKP',
  'Saint Helena': 'SHP',
  Macao: 'MOP',
  'North Korea': 'KPW',
  Palestine: 'ILS',
  Kosovo: 'EUR',
  Montenegro: 'EUR',
  Iceland: 'ISK',
};

export const WORLD_COUNTRIES = Object.keys(COUNTRY_CURRENCY_MAP).sort((a, b) => a.localeCompare(b));

export function currencyForCountry(country) {
  if (!country) return 'USD';
  return COUNTRY_CURRENCY_MAP[country] || 'USD';
}
